<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>_02_AuditFlowApplication</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\PNG\AuditFlow Logo.png" />
    <None Remove="Resources\PNG\PurpleLogoImage.png" />
    <None Remove="Resources\Svg\arrow-right-from-bracket-solid-full.svg" />
    <None Remove="Resources\Svg\arrow-up-from-bracket-solid-full.svg" />
    <None Remove="Resources\Svg\business-time-solid-full.svg" />
    <None Remove="Resources\Svg\circle-xmark-solid-full.svg" />
    <None Remove="Resources\Svg\file-image-regular-full.svg" />
    <None Remove="Resources\Svg\file-lines-regular-full.svg" />
    <None Remove="Resources\Svg\file-pdf-regular-full.svg" />
    <None Remove="Resources\Svg\file-regular-full.svg" />
    <None Remove="Resources\Svg\filter-solid-full.svg" />
    <None Remove="Resources\Svg\flag-regular-full.svg" />
    <None Remove="Resources\Svg\gear-solid-full.svg" />
    <None Remove="Resources\Svg\list-solid-full.svg" />
    <None Remove="Resources\Svg\magnifying-glass-solid-full.svg" />
    <None Remove="Resources\Svg\pen-to-square-solid-full.svg" />
    <None Remove="Resources\Svg\xmark-solid-full.svg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.5" />
    <PackageReference Include="SharpVectors" Version="1.8.5" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\PNG\AuditFlow Logo.png" />
    <Resource Include="Resources\PNG\AuditFlow Purple Logo.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\PNG\TealLogoImage.png" />
    <Resource Include="Resources\PNG\PurpleLogoImage.png" />
    <Resource Include="Resources\Svg\arrow-right-from-bracket-solid-full.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Svg\arrow-up-from-bracket-solid-full.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Svg\business-time-solid-full.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Svg\circle-xmark-solid-full.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Svg\file-image-regular-full.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Svg\file-lines-regular-full.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Svg\file-pdf-regular-full.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Svg\file-regular-full.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Svg\filter-solid-full.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Svg\flag-regular-full.svg" />
    <Resource Include="Resources\Svg\gear-solid-full.svg" />
    <Resource Include="Resources\Svg\list-solid-full.svg" />
    <Resource Include="Resources\Svg\magnifying-glass-solid-full.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Svg\pen-to-square-solid-full.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Svg\square-check-regular-full.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Svg\xmark-solid-full.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
